name: research_package
description: A Flutter framework for obtaining informed consent, showing surveys and collecting results.
version: 0.6.1
homepage: https://github.com/cph-cachet/research.package

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  carp_core: ^0.30.0 # the core CARP domain model

  signature: ^4.1.1
  rxdart: ^0.26.0
  json_annotation: ^4.0.1
  flutter_localizations:
    sdk: flutter
  collection: ^1.15.0
  simple_html_css: ^3.0.1

dev_dependencies:
  # flutter_test:
  #   sdk: flutter
  build_runner: ^2.0.5
  json_serializable: ^4.1.3
  
  test: ^1.17.9

flutter:
  assets:
    - assets/icons/
    - assets/lang/

